package com.test.ssmc.myscreen.Views.greendao.dao;


import com.test.ssmc.myscreen.Views.greendao.HistoryRecord;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig companyDaoConfig;

    private final HistoryRecordDao companyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        companyDaoConfig = daoConfigMap.get(HistoryRecordDao.class).clone();
        companyDaoConfig.initIdentityScope(type);

        companyDao = new HistoryRecordDao(companyDaoConfig, this);

        registerDao(HistoryRecord.class, companyDao);
    }
    
    public void clear() {
        companyDaoConfig.clearIdentityScope();
    }

    public HistoryRecordDao getCompanyDao() {
        return companyDao;
    }

}
